# This is a basic workflow to help you get started with Actions

name: KeyboardNinja

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Install clang-format
        run: sudo apt install clang-format-12

      - name: Check codestyle
        run: git ls-files src/ | xargs clang-format -i && git diff --exit-code
        
      - name: Run make
        run: make
        
      - name: Run Tests
        run: ./bin/testGameClass